const KEY='KIRI2027_FULL_ASSISTANT_v3';
const uid=()=>crypto.randomUUID?.()||Date.now()+Math.random();
const today=()=>new Date().toISOString().slice(0,10);
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0));
const daysUntil=d=>d?Math.ceil((new Date(d+'T23:59:59')-new Date())/86400000):9999;
const clone=o=>structuredClone(o);
const defaults={version:3,settings:{name:'',salaryDate:'',wake:'09:00',sleep:'00:30',workStart:'10:00',workEnd:'21:00'},tasks:[],goals:[
{id:'g1',name:'Стабилизироваться в России',area:'documents',subtasks:[['Документы и сроки',false],['Официальная работа / учёба',false],['Медицинские вопросы',false]]},
{id:'g2',name:'Финансовая стабильность',area:'money',subtasks:[['Контроль расходов',false],['Накопления',false],['Финансовая подушка',false]]},
{id:'g3',name:'Нормальное жильё',area:'housing',subtasks:[['Найти варианты',false],['Рассчитать бюджет',false],['Обустройство',false]]},
{id:'g4',name:'Тело и форма',area:'body',subtasks:[['Стабилизировать вес',false],['Тренировки 3 раза в неделю',false],['Сон и восстановление',false]]},
{id:'g5',name:'Японский язык',area:'japanese',subtasks:[['Хирагана',false],['Катакана',false],['N5',false],['N4',false]]},
{id:'g6',name:'Образование и профессия',area:'education',subtasks:[['Исследовать варианты',false],['Проверить лицензию / аккредитацию',false],['План поступления',false]]},
{id:'g7',name:'Нормальные отношения',area:'relationships',subtasks:[['Свои интересы',false],['Время вместе',false]]},
{id:'g8',name:'Не выгореть',area:'self',subtasks:[['Сон',false],['Отдых',false],['Дни без перегруза',false]]}],
japanese:{chars:[['あ','a'],['い','i'],['う','u'],['え','e'],['お','o'],['か','ka'],['き','ki'],['く','ku'],['け','ke'],['こ','ko']],reviews:{},errors:[],sessions:[],streak:0,lastStudy:null,minutes:0},
body:{measurements:[],workouts:[],weightGoal:80},money:{transactions:[],goals:[{id:'m1',name:'Накопить 90 000 ₽',target:90000,saved:0}]},documents:[],education:[],housing:[],journal:[],chat:[],energy:3,sleepHours:7};
let S=load(),view='today',modal=null;
function load(){try{return merge(clone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return clone(defaults)}}
function merge(a,b){for(const k of Object.keys(b||{})){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object')merge(a[k],b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function progressGoal(g){const a=g.subtasks||[];return a.length?Math.round(a.filter(x=>x[1]).length/a.length*100):0}
function areaProgress(area){const g=S.goals.filter(x=>x.area===area);return g.length?Math.round(g.reduce((a,x)=>a+progressGoal(x),0)/g.length):0}
function money(){return S.money.transactions.reduce((a,x)=>a+Number(x.amount||0),0)}
function income(){return S.money.transactions.filter(x=>x.amount>0).reduce((a,x)=>a+Number(x.amount),0)}
function expenses(){return Math.abs(S.money.transactions.filter(x=>x.amount<0).reduce((a,x)=>a+Number(x.amount),0))}
function dailyLimit(){const balance=money();const d=S.settings.salaryDate?Math.max(1,daysUntil(S.settings.salaryDate)):30;return Math.max(0,Math.floor(balance/d))}
function taskScore(t){let s=(t.priority||2)*30;if(t.date){const d=daysUntil(t.date);s+=d<0?60:d===0?45:d<=3?30:d<=7?18:0}if(t.energy<=S.energy)s+=12;else s-=8;if(t.area&&areaProgress(t.area)<40)s+=8;if(t.duration<=30)s+=5;return s}
function tasksForToday(){return S.tasks.filter(t=>!t.done&&(!t.date||t.date<=today())).sort((a,b)=>taskScore(b)-taskScore(a))}
function dateLabel(){return new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}
function daysText(d){const n=daysUntil(d);if(n<0)return 'просрочено';if(n===0)return 'сегодня';if(n===1)return 'завтра';return `через ${n} дн.`}
function nav(){const items=[['today','⌂','Сегодня'],['goals','◎','Цели'],['japanese','あ','Японский'],['body','⌁','Тело'],['more','⋯','Ещё']];return `<nav class="nav">${items.map(x=>`<button class="${view===x[0]?'active':''}" data-view="${x[0]}"><span class="ni">${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function top(sub=''){return `<header class="top"><div class="brand">KIRI 2027<small>${sub||'твой личный помощник'}</small></div><button class="iconbtn" data-action="assistant">✦</button></header>`}
function head(title,sub=''){return `${top()}<div class="page"><button class="back" data-view="today">← Сегодня</button><h1>${title}</h1><p class="muted">${sub}</p></div>`}
function render(){document.querySelector('#app').innerHTML=`<div class="app"><main class="shell">${view==='today'?todayPage():page(view)}</main>${nav()}</div>${modal?modalHtml():''}`;bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function todayPage(){const ts=tasksForToday().slice(0,3);const doc=S.documents.filter(x=>daysUntil(x.date)<=14).length;return `${top()}<section class="hero"><div class="eyebrow">Сегодня · ${dateLabel()}</div><h1>Твой фокус.</h1><p class="muted">KIRI выбирает главное по дедлайнам, целям, энергии и твоим обстоятельствам.</p></section><section class="focus"><div class="focushead"><strong>Главное на сегодня</strong><div class="actions"><span class="pill">энергия ${S.energy}/5</span><button class="link" data-action="task">+ задача</button></div></div>${ts.length?ts.map((t,i)=>`<div class="focusitem"><span class="num">${i+1}</span><div class="rowmain"><b>${esc(t.title)}</b><small>${t.date?daysText(t.date):'без дедлайна'} · ${t.duration||20} мин</small></div><input class="check" type="checkbox" data-task="${t.id}"></div>`).join(''):`<div class="empty">На сегодня нет обязательных задач. Можно оставить пространство для жизни.</div>`}</section><div class="grid">${[['🇯🇵','Японский','закрепить あ–こ','japanese'],['🏋️','Тело',lastWeight(),'body'],['💰','Финансы',`${fmt(money())} ₽ · лимит ${fmt(dailyLimit())} ₽/день`,'money'],['📄','Документы',doc?`${doc} срока требуют внимания`:'всё спокойно','documents']].map(x=>`<button class="card module" data-view="${x[3]}"><span class="emoji">${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><section class="section card"><div class="sectiontitle"><h2>Состояние</h2><button class="link" data-action="state">изменить</button></div><div class="metric"><span>Энергия</span><strong>${S.energy}/5</strong></div><div class="progress"><i style="width:${S.energy*20}%"></i></div><div class="metric space"><span>Сон</span><strong>${S.sleepHours} ч</strong></div></section><section class="section card mini-assistant"><div><span class="eyebrow">KIRI</span><h2>Что сейчас важнее?</h2><p class="muted">Расскажи про свой день обычными словами.</p></div><button class="btn primary" data-action="assistant">Спросить</button></section>`}
function lastWeight(){const x=S.body.measurements.at(-1);return x?`${x.weight} кг · талия ${x.waist||'—'} см`:'добавь измерение'}
function page(v){const map={goals:goalsPage,japanese:japanesePage,body:bodyPage,money:moneyPage,documents:documentsPage,education:educationPage,housing:housingPage,journal:journalPage,progress:progressPage,assistant:assistantPage,more:morePage};return (map[v]||todayPage)()}
function goalsPage(){return `${head('Цели 2027','Большие цели связаны с реальными действиями.')}${S.goals.map(g=>`<section class="section card"><div class="sectiontitle"><h2>${esc(g.name)}</h2><b>${progressGoal(g)}%</b></div><div class="progress"><i style="width:${progressGoal(g)}%"></i></div><div class="list">${g.subtasks.map((x,i)=>`<label class="row"><input class="check" type="checkbox" data-goal="${g.id}" data-sub="${i}" ${x[1]?'checked':''}><span class="rowmain">${esc(x[0])}</span></label>`).join('')}</div></section>`).join('')}`}
function japanesePage(){const due=S.japanese.chars.filter(c=>(S.japanese.reviews[c[0]]||0)<=Date.now());return `${head('Японский','Сейчас не гонимся дальше あ–こ. Сначала закрепляем основу.') }<div class="statgrid"><div class="card stat"><small>Уровень</small><strong>Pre-N5</strong></div><div class="card stat"><small>Серия</small><strong>${S.japanese.streak}</strong></div><div class="card stat"><small>Ошибки</small><strong>${S.japanese.errors.length}</strong></div><div class="card stat"><small>Минут</small><strong>${S.japanese.minutes}</strong></div></div><section class="section card"><h2>Карточки на повторение</h2><div class="actions">${(due.length?due:S.japanese.chars).map(c=>`<button class="btn" data-action="jp-card" data-char="${c[0]}" data-romaji="${c[1]}">${c[0]}</button>`).join('')}</div><p class="muted">Нажми знак и попробуй вспомнить чтение до подсказки.</p></section><section class="section card"><h2>Мини-тест</h2><button class="btn primary" data-action="jp-test">Проверить себя</button></section><section class="section card"><h2>Слова, которые уже встречались</h2><p>いえ — дом · あお — синий · うえ — верх · あい · おい</p></section>`}
function bodyPage(){const w=S.body.measurements.at(-1);return `${head('Тело','Данные помогают видеть тенденцию, а не ругать себя.') }<div class="statgrid"><div class="card stat"><small>Вес</small><strong>${w?w.weight:'—'} кг</strong></div><div class="card stat"><small>Талия</small><strong>${w?.waist||'—'} см</strong></div><div class="card stat"><small>Цель</small><strong>${S.body.weightGoal} кг</strong></div><div class="card stat"><small>Тренировок</small><strong>${S.body.workouts.length}</strong></div></div><section class="section card"><div class="sectiontitle"><h2>Измерения</h2><button class="btn primary" data-action="measure">+ добавить</button></div>${S.body.measurements.slice(-8).reverse().map(x=>`<div class="row"><span class="rowmain"><b>${x.weight} кг</b><small>${x.date} · талия ${x.waist||'—'} см</small></span></div>`).join('')||'<div class="empty">Пока нет измерений.</div>'}</section><section class="section card"><div class="sectiontitle"><h2>Тренировки</h2><button class="btn primary" data-action="workout">+ тренировка</button></div>${S.body.workouts.slice(-8).reverse().map(x=>`<div class="row"><span class="rowmain"><b>${esc(x.name)}</b><small>${x.date} · ${x.duration} мин</small></span></div>`).join('')||'<div class="empty">История тренировок появится здесь.</div>'}</section><section class="section card"><h2>Базовая тренировка</h2><p class="muted">Пример для новичка: присед с гантелью — держишь гантель у груди и садишься назад; тяга одной гантели — наклонись с ровной спиной и тяни гантель к поясу; жим гантелей — выжимай вверх без рывков.</p></section>`}
function moneyPage(){const goal=S.money.goals[0];const saved=Math.max(0,money());const pct=goal?Math.min(100,Math.round(saved/goal.target*100)):0;return `${head('Финансы','KIRI считает фактический баланс и простой ориентир до зарплаты.') }<div class="statgrid"><div class="card stat"><small>Баланс</small><strong>${fmt(money())} ₽</strong></div><div class="card stat"><small>Доходы</small><strong>${fmt(income())} ₽</strong></div><div class="card stat"><small>Расходы</small><strong>${fmt(expenses())} ₽</strong></div><div class="card stat"><small>В день</small><strong>${fmt(dailyLimit())} ₽</strong></div></div><section class="section card"><div class="sectiontitle"><h2>Накопление</h2><b>${pct}%</b></div><div class="progress"><i style="width:${pct}%"></i></div><p class="muted">Цель ${fmt(goal?.target||0)} ₽ · осталось ${fmt(Math.max(0,(goal?.target||0)-saved))} ₽</p></section><section class="section card"><div class="sectiontitle"><h2>Операции</h2><button class="btn primary" data-action="money">+ операция</button></div>${S.money.transactions.slice(-12).reverse().map(x=>`<div class="row"><span class="rowmain"><b>${esc(x.category)}</b><small>${x.date}</small></span><strong class="${x.amount>=0?'positive':'negative'}">${x.amount>=0?'+':''}${fmt(x.amount)} ₽</strong></div>`).join('')||'<div class="empty">Добавь первый доход или расход.</div>'}</section>`}
function documentsPage(){const sorted=[...S.documents].sort((a,b)=>new Date(a.date)-new Date(b.date));return `${head('Документы','Дедлайны срабатывают заранее: 14, 7, 3 дня и в день срока.') }<button class="btn primary" data-action="document">+ документ</button><section class="section list">${sorted.map(x=>`<div class="card"><div class="sectiontitle"><h2>${esc(x.name)}</h2><span class="pill ${daysUntil(x.date)<=7?'danger':''}">${daysText(x.date)}</span></div><p class="muted">${x.date} · ${esc(x.status||'нужно проверить')}</p></div>`).join('')||'<div class="empty">Пока нет документов. Добавляй только реальные сроки.</div>'}</section>`}
function educationPage(){return `${head('Образование','Сравниваем стоимость, документы, формат и совместимость с работой.') }<button class="btn primary" data-action="education">+ вариант</button><section class="section list">${S.education.map(x=>`<div class="card"><div class="sectiontitle"><h2>${esc(x.name)}</h2><span class="pill">${esc(x.status)}</span></div><p>${esc(x.cost||'')}</p></div>`).join('')||'<div class="empty">Сохраняй сюда учебные заведения и программы, которые реально рассматриваешь.</div>'}</section>`}
function housingPage(){return `${head('Жильё','Ориентир: Москва, 35–40 тыс. ₽/месяц, желательно рядом с метро.') }<button class="btn primary" data-action="housing">+ вариант</button><section class="section list">${S.housing.map(x=>`<div class="card"><div class="sectiontitle"><h2>${esc(x.name)}</h2><b>${fmt(x.price)} ₽</b></div><span class="pill">${esc(x.status)}</span></div>`).join('')||'<div class="empty">Добавляй квартиры, которые реально стоит сравнить.</div>'}</section><section class="section card"><h2>Идея пространства</h2><p class="muted">Чёрный · loft · Japanese · минимализм. Идею металлической штанги 3,8–3,9 м можно сохранить как отдельную покупку после переезда.</p></section>`}
function journalPage(){return `${head('Дневник','Пиши обычными словами. Здесь не нужно быть продуктивным.') }<button class="btn primary" data-action="journal">+ запись</button><section class="section list">${S.journal.slice(-10).reverse().map(x=>`<div class="card"><div class="muted">${x.date} · настроение ${x.mood}/5 · энергия ${x.energy}/5 · сон ${x.sleep} ч</div><p>${esc(x.text)}</p></div>`).join('')||'<div class="empty">Первая запись появится здесь.</div>'}</section>`}
function progressPage(){const areas=[['documents','Россия / документы','📄'],['money','Финансы','💰'],['body','Тело','🏋️'],['japanese','Японский','🇯🇵'],['education','Образование','🎓'],['housing','Жильё','🏠'],['relationships','Отношения','♡'],['self','Саморазвитие','✦']];return `${head('Прогресс 2027','Проценты строятся из отмеченных подзадач.') }<section class="section list">${areas.map(a=>`<div class="card"><div class="metric"><span>${a[2]} ${a[1]}</span><b>${areaProgress(a[0])}%</b></div><div class="progress"><i style="width:${areaProgress(a[0])}%"></i></div></div>`).join('')}</section>`}
function assistantPage(){return `${head('Помощник KIRI','Можно писать обычным языком: про работу, деньги, усталость, японский или весь день сразу.') }<section class="section card"><div class="chat">${S.chat.slice(-12).map(m=>`<div class="bubble ${m.role==='user'?'me':'kiri'}">${esc(m.text)}</div>`).join('')||'<div class="empty">Например: «Я завтра работаю до 21, денег мало и хочу не забросить японский».</div>'}</div><div class="form"><textarea id="ask" class="textarea" placeholder="Что происходит сегодня?"></textarea><button class="btn primary" data-action="ask">Спросить KIRI</button></div></section>`}
function morePage(){return `${head('Ещё','Все остальные разделы KIRI.') }<div class="grid">${[['💰','Финансы','money'],['📄','Документы','documents'],['🎓','Образование','education'],['🏠','Жильё','housing'],['📓','Дневник','journal'],['◉','Прогресс','progress'],['✦','Помощник KIRI','assistant']].map(x=>`<button class="card module" data-view="${x[2]}"><span class="emoji">${x[0]}</span><b>${x[1]}</b></button>`).join('')}</div><section class="section card"><h2>Резервная копия</h2><div class="actions"><button class="btn primary" data-action="export">Скачать JSON</button><button class="btn" data-action="import">Восстановить</button><button class="btn dangerbtn" data-action="reset">Сбросить данные</button></div><input id="importFile" type="file" accept="application/json" hidden></section><section class="section card"><h2>Мой режим</h2><div class="form"><input class="input" id="salaryDate" type="date" value="${S.settings.salaryDate||''}"><label>Подъём<input class="input" id="wake" type="time" value="${S.settings.wake}"></label><label>Сон<input class="input" id="sleep" type="time" value="${S.settings.sleep}"></label><label>Работа с<input class="input" id="workStart" type="time" value="${S.settings.workStart}"></label><label>Работа до<input class="input" id="workEnd" type="time" value="${S.settings.workEnd}"></label><button class="btn primary" data-action="saveSettings">Сохранить</button></div></section>`}
function modalHtml(){if(modal.type==='assistant')return `<div class="modal"><div class="sheet"><button class="iconbtn close" data-action="close">×</button><h2>Спросить KIRI</h2><div class="chat">${S.chat.slice(-8).map(m=>`<div class="bubble ${m.role==='user'?'me':'kiri'}">${esc(m.text)}</div>`).join('')}</div><div class="form"><textarea id="ask" class="textarea" placeholder="Например: я устал после работы, денег мало, хочу японский..."></textarea><button class="btn primary" data-action="ask">Отправить</button></div></div></div>`;const f={task:['Новая задача','Что нужно сделать','Дата YYYY-MM-DD'],measure:['Новое измерение','Вес (кг)','Талия (см)'],money:['Операция','Сумма: доход + / расход -','Категория'],document:['Документ','Название','Дата YYYY-MM-DD'],education:['Образование','Учебное заведение','Стоимость / программа'],housing:['Жильё','Район / ссылка / название','Цена в ₽'],journal:['Дневник','Текст','Настроение 1–5'],workout:['Тренировка','Что делал','Длительность в минутах']}[modal.type];if(f)return `<div class="modal"><div class="sheet"><button class="iconbtn close" data-action="close">×</button><h2>${f[0]}</h2><div class="form"><input class="input" id="f1" placeholder="${f[1]}"><input class="input" id="f2" placeholder="${f[2]}"><button class="btn primary" data-action="submitForm">Сохранить</button></div></div></div>`;return ''}
function open(t){modal={type:t};render()}
function localAssistant(q){const l=q.toLowerCase();const work=S.settings.workEnd?`Работа обычно до ${S.settings.workEnd}. `:'';if(/денег|рубл|бюджет|потрат/.test(l))return `Сейчас в KIRI записано ${fmt(money())} ₽. ${S.settings.salaryDate?`До зарплаты примерно ${daysUntil(S.settings.salaryDate)} дн.; ориентир без учёта обязательных платежей — около ${fmt(dailyLimit())} ₽ в день.`:'Дата зарплаты пока не задана.'} Сначала оставляем резерв на обязательное, потом распределяем остаток.`;if(/устал|не хочу|ничего не хочу|выгор/.test(l))return `Окей. Сегодня не надо героизма. Режим минимума: поесть, 10–20 минут японского без новой темы, душ и сон. ${work}Тяжёлую тренировку можно перенести.`;if(/япон|хираган/.test(l))return `Сегодня держимся только あ–こ. 10–20 минут: вспомнить знаки без подсказки, прочитать いえ・あお・うえ・あい・おい и отдельно повторить самые слабые знаки. Новую строку пока не добавляем.`;if(/трен|спорт|зал/.test(l))return S.energy<3?`Энергия ${S.energy}/5 — тяжёлую тренировку сегодня лучше не делать. Можно 10–20 минут спокойного движения или перенести занятие.`:`Энергия ${S.energy}/5 позволяет короткую тренировку на 20–30 минут: присед с гантелью, тяга одной гантели, жим гантелей и немного корпуса. Техника важнее веса.`;const t=tasksForToday().slice(0,3);return `Я посмотрел на текущую систему. Сейчас главное: ${t.length?t.map((x,i)=>`${i+1}) ${x.title}`).join('; '):'обязательных задач нет'}. Если день тяжёлый — можно оставить только одну главную задачу и японский на 10 минут.`}
async function askKiri(){const q=document.querySelector('#ask')?.value.trim();if(!q)return;S.chat.push({role:'user',text:q});save();render();modal={type:'assistant'};try{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,context:{tasks:S.tasks,goals:S.goals,energy:S.energy,sleep:S.sleepHours,money:S.money,body:S.body,japanese:S.japanese,documents:S.documents,settings:S.settings}})});if(r.ok){const j=await r.json();S.chat.push({role:'kiri',text:j.reply||localAssistant(q)})}else throw 0}catch{S.chat.push({role:'kiri',text:localAssistant(q)})}save();render()}
function formSubmit(){const a=document.querySelector('#f1')?.value.trim(),b=document.querySelector('#f2')?.value.trim();if(!a)return;switch(modal.type){case'task':S.tasks.push({id:uid(),title:a,date:b||today(),priority:3,duration:20,energy:S.energy,area:'self',done:false});break;case'measure':S.body.measurements.push({date:today(),weight:Number(a),waist:Number(b)||null});break;case'money':S.money.transactions.push({id:uid(),date:today(),amount:Number(a.replace(',','.')),category:b||'прочее'});break;case'document':S.documents.push({id:uid(),name:a,date:b||today(),status:'нужно проверить'});break;case'education':S.education.push({id:uid(),name:a,cost:b||'',status:'рассматриваю'});break;case'housing':S.housing.push({id:uid(),name:a,price:Number(b.replace(',','.'))||0,status:'смотрю'});break;case'journal':S.journal.push({id:uid(),date:today(),text:a,mood:Math.max(1,Math.min(5,Number(b)||3)),energy:S.energy,sleep:S.sleepHours});break;case'workout':S.body.workouts.push({id:uid(),date:today(),name:a,duration:Number(b)||20});break}save();modal=null;render()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;modal=null;render()});document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{const t=S.tasks.find(t=>t.id===x.dataset.task);if(t){t.done=x.checked;save();render()}});document.querySelectorAll('[data-goal]').forEach(x=>x.onchange=()=>{const g=S.goals.find(g=>g.id===x.dataset.goal);if(g){g.subtasks[Number(x.dataset.sub)][1]=x.checked;save();render()}});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action;if(a==='assistant')open('assistant');if(a==='close'){modal=null;render()}if(['task','measure','money','document','education','housing','journal','workout'].includes(a))open(a);if(a==='submitForm')formSubmit();if(a==='ask')askKiri();if(a==='jp-card'){const c=b.dataset.char,r=b.dataset.romaji;S.japanese.reviews[c]=Date.now()+172800000;S.japanese.lastStudy=today();S.japanese.minutes+=3;save();toast(`${c} — ${r}`);render()}if(a==='jp-test'){const c=S.japanese.chars[Math.floor(Math.random()*S.japanese.chars.length)];const answer=prompt(`Как читается ${c[0]}?`);if(answer?.trim().toLowerCase()===c[1]){S.japanese.reviews[c[0]]=Date.now()+345600000;S.japanese.lastStudy=today();S.japanese.streak=Math.max(1,S.japanese.streak+1);S.japanese.minutes+=5;toast('Верно ✓')}else{S.japanese.errors.push({char:c[0],date:today(),answer:answer||''});toast(`Правильно: ${c[1]}`)}save();render()}if(a==='state'){const e=prompt('Энергия от 1 до 5',S.energy);if(e){S.energy=Math.max(1,Math.min(5,Number(e)));save();render()}}if(a==='export'){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),x=document.createElement('a');x.href=url;x.download=`KIRI2027-backup-${today()}.json`;x.click();URL.revokeObjectURL(url)}if(a==='import')document.querySelector('#importFile')?.click();if(a==='reset'&&confirm('Удалить локальные данные KIRI?')){localStorage.removeItem(KEY);S=load();render()}if(a==='saveSettings'){S.settings.salaryDate=document.querySelector('#salaryDate').value;S.settings.wake=document.querySelector('#wake').value;S.settings.sleep=document.querySelector('#sleep').value;S.settings.workStart=document.querySelector('#workStart').value;S.settings.workEnd=document.querySelector('#workEnd').value;save();toast('Настройки сохранены');render()}});document.querySelector('#importFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{S=merge(clone(defaults),JSON.parse(r.result));save();render();toast('Резервная копия восстановлена')}catch{toast('Не удалось прочитать JSON')}};r.readAsText(f)})}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
if(!localStorage.getItem(KEY)){S.tasks=[{id:uid(),title:'Закрепить あ–こ',date:today(),priority:3,duration:20,energy:2,area:'japanese',done:false},{id:uid(),title:'Проверить ближайший документный дедлайн',date:today(),priority:3,duration:15,energy:2,area:'documents',done:false},{id:uid(),title:'20–30 минут движения',date:today(),priority:2,duration:25,energy:3,area:'body',done:false}];save()}
render();
